# Generated by Django 3.0.2 on 2020-02-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0002_auto_20200211_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='wasif',
        ),
    ]
