# Generated by Django 3.0.2 on 2020-06-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0003_auto_20200211_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='wasif',
            new_name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist_name',
            field=models.ManyToManyField(to='zing_it.Playlist'),
        ),
    ]
